// auth action types
export const IS_LOGIN = 'IS_LOGIN';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


//NEED TO WORK ON FAILED THINGS AND ALERT BOX


// event action types
export const EVENT_SUCCESS = 'EVENT_SUCCESS';
export const EVENT_INITIATE ='EVENT_INITIATE';
export const EVENTS_SUCCESS ='EVENTS_SUCCES';
export const EVENTS_INITIATE = 'EVENTS_INITIATE';
export const BOOK_EVENT_INITIATE = 'BOOK_EVENT_INITIATE';
export const CLOSE_ALERT_EVENT ='CLOSE_ALERT_EVENT';
export const SPINNER_TOGGLE = 'SPINNER_TOGGLE';


// booking action types
export const BOOKINGS_INITIATE = 'BOOKINGS_INITIATE';
export const BOOKINGS_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_DELETE = 'BOOKING_DELETE';
export const BOOKING_DELETE_SUCCESS = 'BOOKING_DELETE_SUCCESS';